### ISSUE TITLE
boolean option is ignored if starts with 'no-'

### ISSUE THREAD

**Issue by vadimadr** [yeoman/generator#1000]
I have yeoman generator that should accept options like this:
```js
    this.option('no-yarn', {
      desc: 'Do not use yarn for installing node dependencies',
      type: Boolean,
      default: false
    });
```

However, even if generator started with `yo mygen --no-yarn`, option is completely ignored:
```js
  initialising: function () {
   // prints: no yarn : false
    this.log(`no yarn : ${this.options['no-yarn']}`);
   }
```

But if I change name of option to smth like 'noyarn' it works as expected.

```
$ yo --version
1.8.5
``` 
```
yeoman-generator@0.24.1
```

**Comment by SBoudrias** [comment]
Oh yeah, that's related to the args parsing libraries. Basically, any `no-` prefix is considered as boolean.

So in this case what happened is that the parsing library will define `--no-yarn` as `{yarn: false}`. Yeoman on the side will look for an option called `no-yarn` and because the args parsing only defined a `yarn` argument, we don't find it.

What you want is `this.option('yarn', {type: Boolean})`. This will effectively allow `--no-yarn`.

-------------------

This is not a behavior we can change in Yeoman because of how coupled this behavior is to the environment. That being said, this behavior is pretty sane and match the behavior of other command line tools; this is not a "yeoman thing".

We should however explicitly validate the names of options and throw a useful exception when trying to define a name that won't work.

**Comment by addyosmani** [comment]
> We should however explicitly validate the names of options and throw a useful exception when trying to define a name that won't work.

That sounds entirely reasonable to me. @vadimadr @milindl if either of you are interested in working on a PR for this, we would be happy to give you pointers.

**Comment by SBoudrias** [comment]
Actually a PR was sent and merged, so that issue is now fixed :)
