### ISSUE TITLE
Could not find matching close tag for "<%"

### ISSUE THREAD

**Issue by GZWZC** [yeoman/generator#1031]
/app/index.js
```
var generators = require('yeoman-generator');  
var path = require('path');  

module.exports = generators.Base.extend({
    generateBasic: function() {  //按照自己的templates目录自定义
        this.directory('build', 'build');    //拷贝目录
    },
    end:function(){
        console.log('构建完毕')
    }
});
```

when i yo generator-test，cmd console  Could not find matching close tag for "<%"，this directory is not a function?  build is my floder

**Comment by mischah** [comment]
Hej @GZWZC,

its seems that you want to use the `copy` method instead of the non existing `directory` method.

See this for an overview:
http://yeoman.io/authoring/file-system.html

and this for an overview about additional methods to interact with the file system:
https://github.com/sboudrias/mem-fs-editor 

Feel free to ask for help in the generator gitter room if you get stuck:
https://gitter.im/yeoman/generator

**Comment by GZWZC** [comment]
@mischah Thank you, I solved it
