### ISSUE TITLE
Compose same generator but with different options

### ISSUE THREAD

**Issue by ephracis** [yeoman/generator#1055]
Is it possible to have generator A call generator B multiple times but with different input?

For example if `generator:book` asks the user prompts like:
- Name of book
- Number of chapters
- Name of author

Then it creates the book, and calls a second generator `generator:chapter` which asks the user the title of the chapter and creates the necessary files.

When I try to do this I seem to get the same input in all runs of the second generator. Even though the constructor receives different input.

**Comment by SBoudrias** [comment]
Hey @ephracis, this should be possible. If it doesn't work, then there's a bug somewhere.

I'll away from my computer for the next 2 weeks, so I won't have time to help you troubleshoot the issues. Could you provide a reduced demo with code we can run directly to see what happens? This would go a long way to help us debug the issue - and by doing so, you might even find the bug if it turns out it's on your side.

**Comment by ephracis** [comment]
My current code is really huge so I would need to spend some time setting up a demo example. Unfortunately I won't have time to do this until late next week.

In the meantime, I have narrowed the issue down to the runQueue. When the methods are added I can see all the correct params on `self`, but when if I inspect `self` inside the methods themselves, they all contain the same data which is the input from the LAST composed generator.

It seems to be that this is due to how prototyping works in Javascript. Basically Yeoman (or runQueue) uses the "class" as context, not "instance".
