### ISSUE TITLE
scheduleInstallTask to fail incase installer fails and output the error

### ISSUE THREAD

**Issue by regevbr** [yeoman/generator#1080]
If the generator decided to run an installer, the process should fail if the installer fails...
Also need to print the error from the installer as it is hard to debug the issue.
This should be a 2 liner fix the only question is if the current behavior is intentional.

**Comment by SBoudrias** [comment]
Hey @regevbr the behavior is intentional in so far we prefer the user to debug installer issues with the tool directly without Yeoman. So what we do is print the error message (installer fails, please run xxxxx yourself.)

I'm not against adding the actual error message to the output, but what happens when we do this is literally hundreds of people open issues on Yeoman repositories about installation errors as they believe it comes from `yo`. This for us was unmaintainable and we couldn't keep up with the noise.

I think current solution helped a lot clear the useless issue clutter.

**Comment by regevbr** [comment]
@sboudrias i understand your concerns and ill give my reasoning for both requests :
- im ny case the error was that bower wasn't in my yo path for some reason and when I ran it myself it worked ao i had to debug your code to realize the error. Maybe just add the error message in case of execution issues.
- i run generators automation and if the generator doesn't fail that causes major issues as it produces invalid artifacts... I really believe it should fail the rub

**Comment by SBoudrias** [comment]
I wouldn't mind having an `exit 1` status code if installation fail to make it easier to catch, but I don't think it should kill the generator process as installation isn't require (e.g. `--skip-install`)

About the error message, would it make sense to print the message if you run with a `--verbose` flag? And keep it as is if run normally.

**Comment by regevbr** [comment]
Both sounds great

**Comment by SBoudrias** [comment]
Alright, I think this would be good changes then. Would you be interested to send PRs? I don't think I'll have time to work on this soon; I have some other OSS tasks that are higher priority for me.

**Comment by regevbr** [comment]
Ill do it no problem. Still waiting for code review on my env pr :-)

**Comment by regevbr** [comment]
@SBoudrias --skip-install doesn't install alltogether so what do you want the behaviour to be in case of error or bad exit code? Maybe we need to add another falg to it that will accumulate the verbose suggestion as well?
