### ISSUE TITLE
Separate user/author defined options from yeoman internal options

### ISSUE THREAD

**Issue by desidia26** [yeoman/generator#1180]
**Feature**:
Currently to access user supplied options/options that the author of the generator defines, that author must reference the `this.options` object. This object contains what looks to be yeoman internal data such as

`  

    env: Environment {

    _events: [Object: null prototype] { error: [Function] },

    _eventsCount: 1,

    _maxListeners: undefined,

    arguments: [],

    options: {},

    adapter: TerminalAdapter { promptModule: [Function] },

    store: Store {

      _generators: [Object],

      _meta: [Object],

      _packagesPaths: [Object],

      _packagesNS: [Array]

    },

    runLoop: Queue {

      queueNames: [Array],

      __queues__: [Object],

      _maxListeners: 0

    },

    sharedFs: Store {

      _events: [Object: null prototype] {},

      _eventsCount: 0,

      _maxListeners: 0

    },

    lookups: [ '.', 'generators', 'lib/generators' ],

    aliases: [ [Object] ],

    sharedOptions: { sharedData: {} }

`

It would be helpful to separate these from user/author defined options so that option validation could be done more easily.

**Use case**: I have a generator where I wish to check and see if the user has passed an argument that I don't account for, and notify them.

**Comment by mshima** [comment]
It's possible to pass environments defined options on another constructor parameter to Generator.
https://github.com/yeoman/environment/blob/5c77b3ed017ab5b3f3e4aafe544f8a2b8b1d60a6/lib/environment.js#L547-L555

But generator's ones cannot be differentiated.
https://github.com/yeoman/generator/blob/3d8374b31df289b87c6f57fb3f87b76c73b541c4/lib/index.js#L820-L830

At last and most important is that the options passed at the second parameter should not be changed for backward compatibility
We are not breaking backward compatibility for this feature.
Ex: this.options.namespace is used in a lot of places, this.options.env is used since at least generator 1.0.0.

So its needed to subtract environment options from the received options.
A workaround is:
```
const userOptions = {...this.options};
delete userOptions.env;
delete userOptions.resolved;
delete userOptions.namespace;
Object.keys(this.env.sharedOptions).forEach(key => delete userOptions[key]);
['skipInstall', 'skip-install', 'skipCache', 'skip-cache', 'forceInstall', 'force-install'].forEach(key => delete userOptions[key]);
```
