### ISSUE TITLE
Custom Conflictor?

### ISSUE THREAD

**Issue by bstopp** [yeoman/generator#1250]
Forgive me if this isn't the correct place for this - but I couldn't find anywhere else.

What is the correct way to interact with the conflictor programmatically?

I know in my generator that 3 files should be in conflict - i'm making changes to existing files. 

I want to hook into the Conflictor resolution process, resolve those three files via API calls or whatever, but allow the Conflictor to deal with any other issues that may be raised.

Is this possible?

**Comment by mshima** [comment]
See https://github.com/yeoman/generator/issues/1239#issuecomment-627503894
But the right way to implement is by creating a transform stream.
It would be something like:
```
this.registerTransformStream(
  through.obj(function(file, enc, cb) {
      // If the file has no state requiring action, move on
      if (file.state === null) {
        return cb();
      }
      if (file.path === this.destinationPath('anyfile')) {
        file.conflicter = 'force';
      }
  })
);
```

**Comment by bstopp** [comment]
Is this documented anywhere other than the Issues list? (i went looking through all issues with `conflictor` in the name, saw this but didn't  go digging, like i should have )

**Comment by bstopp** [comment]
Also, does it matter _when_ this gets registered? As in which context? (I would think should put it in `conflicts` but wasn't sure if it was necessary in constructor etc).

**Comment by mshima** [comment]
> Is this documented anywhere other than the Issues list?

Not documented, would be nice to have the transform implementation documented.

> Also, does it matter _when_ this gets registered? As in which context? (I would think should put it in `conflicts` but wasn't sure if it was necessary in constructor etc).

Not sure it will work in the `conflicts` priority. But it's recommended that `conflicts` to be internal use only, not sure were it's documented. I think it's better to put in the constructor.

It should be registered in the root generator, `registerTransformStream` on secondary generators aren't executed at all because conflicter is executed at the root generator before others generators, and all conflicts have been resolved at the time conflicter is run on the others generators https://github.com/yeoman/generator/issues/819.

**Comment by mshima** [comment]
Closing since the question is answered.
@bstopp once you get it working, would be nice if you post your implementation here.

**Comment by htoooth** [comment]
You can use this to allow you to force update the file.

```javascript
conflicts() {
    this.conflicter.force = true
  }
```
