### ISSUE TITLE
Adhere to XDG Base Desktop Specification

### ISSUE THREAD

**Issue by eankeen** [yeoman/generator#1253]
## Type of issue

haii,
i was wondering if there is any interest to adhere to the xdg base desktop specification (on linux), even if it's just a little bit? right now i see a [`~/.yo-rc-global.json`](https://github.com/yeoman/yo/blob/master/lib/utils/global-config.js#L7) file created in the home directory. i mainly would like to see it in `$XDG_CONFIG_HOME/yeoman/yo-rc-global.json` (`~/.config/yeoman/yo-rc-global.json`) to clean up the home directory. i think it would be best for compatibility if we read make the config resolve to `$XDG_CONFIG_HOME/yeoman/yo-rc-global.json`, but only if the `~/.yo-rc-global.json` file doesn't exist - thoughts?. i can make a pr if needed :) more info on the xdg base directory specification can be found [here](https://specifications.freedesktop.org/basedir-spec/latest/index.html#introduction)

thankies,
edwin

**Comment by mshima** [comment]
@eankeen seems like yo never writes to .yo-rc-global.json.
Fell free to create a PR here at generator first, then you can update yo to read from the updated version.

**Comment by mshima** [comment]
If an old generator is called, it will keep writing to `$home/.yo-rc-global.json`.
So:
- generator 1 till 4.11.0 will write exclusively to `$home/.yo-rc-global.json`.
- generator 4.11.0=< x < 5 should write to `$home/.yo-rc-global.json` if it contains the generator namespace, otherwise it should write to `~/.config/yeoman/yo-rc-global.json`
- generator >= 5 should move the generator namespace to `~/.config/yeoman/yo-rc-global.json` if it exist at `$home/.yo-rc-global.json` and don't exists at `~/.config/yeoman/yo-rc-global.json`
