### ISSUE TITLE
yeoman-generator wants conflicting transitive dependencies on mem-fs

### ISSUE THREAD

**Issue by ntucker** [yeoman/generator#1502]
# Fix:
Update @yeoman/types mem-fs dependency to 4

# Problem:
yeoman-generator depends on @yeoman/types and mem-fs@4. But @yeoman/types doesn't like mem-fs@4 - it wants @3.

```bash
mem-fs is listed by your project with version 4.0.0, which doesn't satisfy what @yeoman/types (pac28d) requests (^3.0.0).
```

**Comment by mshima** [comment]
`@yeoman/types` has acceptDependencies field.
https://github.com/yeoman/yeoman-api/blob/6a5bf931273cb1816020797cc34a2d6c73a73deb/workspaces/types/package.json#L59-L61

See https://github.com/npm/rfcs/blob/main/implemented/0023-acceptDependencies.md#motivation.

**Comment by mshima** [comment]
`@yeoman/types` requires node 16 while mem-fs@4 requires node 18.
- it would require a major bump creating incompatibilities between environment and generators types.
- v2 may never happen since it only provides types and it should be stable, no breaking change in types will probably be implemented.

**Comment by LandonSchropp** [comment]
@mshima Just out of curiosity, what are acceptDependencies? I haven't heard of them before this, and I can't seem to find them in the [package.json docs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json) or through Google.
