### ISSUE TITLE
Discussion: Build Process Testing

### ISSUE THREAD

**Issue by passy** [yeoman/generator#211]
The tests in all official generators only cover the scaffolding process and verify the existence of files. We should expand the test coverage to the build process as well, because this is the place where most regressions happen.

Since all generators using a Gruntfile would benefit from some shared setup code, `generator` is probably a good place for this. How could an API for that look like? What should it do?

We already have the ability to run a generator in a subfolder with different prompt options, but we would also need a way to manipulate that folder comfortably to add and remove certain files, run grunt with different options and inspect the result.

/cc @btford @kevva @sindresorhus @addyosmani

**Comment by zckrs** [comment]
I drop a [PR on generator-node](https://github.com/yeoman/generator-node/pull/167/commits).
Maybe it can feed the discussion.

**Comment by deimyts** [comment]
I've been doing this by using the test helpers to generate a project, and then using `exec` to run the grunt tasks:  `exec('grunt build', function()...)`.

The biggest hurdle was working around needing to `npm install` and `bower install` for every variation I wanted to test (also using `exec()`, since I couldn't find a way to easily tell the `.inDir()` function to leave those folders in when it cleans out the test directory, and that made the tests painfully slow. 

Currently, I'm using an npm script to install the packages in another temporary folder, and then using `fs-extra.copy()` to move those into the test directory before running the tests. It's faster than `npm install`, but it's still pretty slow. I'd love to have a better way to do this kind of thing.
 Perhaps the directory-cleaning code could be moved into its own function, which could be passed qualifiers about what to remove?
