### ISSUE TITLE
[Bug v0.18.x] Conflicter always return true on assets files.

### ISSUE THREAD

**Issue by zckrs** [yeoman/generator#717]
I have a issue with https://github.com/Swiip/generator-gulp-angular since we have updated `yeoman-generator` to `0.18.3`  see https://github.com/Swiip/generator-gulp-angular/pull/152
In generator there are [assets files](https://github.com/Swiip/generator-gulp-angular/tree/master/app/templates/src/assets/images).

When I run in serie `yo gulp-angular` to create a new project I always get conflict on all assets files each time. 

![bash](https://cloud.githubusercontent.com/assets/3020368/5328032/a4b0b468-7d6b-11e4-8e1b-27d8cd7edef9.png)
*Between two `yo gulp-angular`  the files have not changed.*

I think [conflicter.js](https://github.com/yeoman/generator/blob/master/lib/util/conflicter.js) not getting the right `file.contents` when checked if a conflict exist on [L111](https://github.com/yeoman/generator/blob/master/lib/util/conflicter.js#L111).

**Comment by xvik** [comment]
Also faced this on java .jar file. Copied it with this.fs.copy()
Don't know the root cause but content (file.content) of new file (which generator is going to store) is different.
So when existing file is read (var actual = fs.readFileSync(path.resolve(filepath))) contents not match.
In my case this "bad" content was almost two times bigger. 
Probably its some encoding problem (tried to save both passed content and actual file, difference was just in encoding). Also tried to compare hex results (actual.toString('hex') and contents.toString('hex') from detect-conflict module): content hex is exactly actual hex + something at the end.

Strange that saved file is correct. Is content used for colission check and actual saved content is not the same?

**Comment by SBoudrias** [comment]
If anyone can provide a reduce test case demonstrating the failure, that'd be super useful to debug as I haven't been able to reproduce on my side.

@xvik insight are helpful, but it'll go faster if I can just clone a repo and reproduce rather than trying multiple combination.

**Comment by xvik** [comment]
Here it is https://github.com/xvik/generator-collision-failure
On second generation it will complain

**Comment by zckrs** [comment]
Thanks for the repo @xvik.

> Also tried to compare hex results (actual.toString('hex') and contents.toString('hex') from detect-conflict module): content hex is exactly actual hex + something at the end.

I noticed the same problem

**Comment by zckrs** [comment]
https://github.com/yeoman/generator/blob/master/lib/base.js#L763
Replace `file.contents.toString()` by `file.contents` solved issue for me. 
Thanks @Toilal

@xvik
