### ISSUE TITLE
Deprecate gruntfile API

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#744]
While the generator system is supposed to be generic this API is highly specific to a use-case.

Would be better for users needing it to just `require()` it themselves.

https://github.com/yeoman/generator/blob/b611741e98710e2737080eab6e8bb5e8521fa4ee/lib/base.js#L157-L179

@SBoudrias Thoughts?

**Comment by eddiemonge** [comment]
I agree if that functionality was pulled into a separate module to keep it easy for end users to still use/require it.

**Comment by SBoudrias** [comment]
By nature, this module cannot be used per case because the point is:

1. Sharing the Gruntfile edition in order to allow composability of multiple configs
2. Being binded to the yeoman in memory file-system

As so, I feel if we expect people to use it, then we must provide the interface inside the generators. Composability is still new and haven't been used a whole lot in our official generators. I believe it is still too early to make a judgement calls on the removal of composability features.

**Comment by SBoudrias** [comment]
A thing we could do though is extract the logic of sharing the Gruntfile to a generator subclass or in a [mixin](https://github.com/yeoman/generator/issues/733). So people who don't need it won't have it.
