### ISSUE TITLE
0.10.7 broke test/helpers.run()

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#771]
Re https://github.com/yeoman/generator-generator/commit/6f068d26e65fddf721dcec44123f41a31a415f7a

Test passes with 0.10.6, but breaks 0.10.7.

-

@SBoudrias

**Comment by SBoudrias** [comment]
Hey, finally got around to investigate this issue.

So actually, it is not a exactly a bug, but it is definitely an edge case with using a memory file system.

The issue is a generator constructor (`generators.Base`) will read multiple config files when instantiated. Notably, it reads `package.json` and `bower.json` to determine the app name. Once these files are loaded in the memory file system, changes occurring on the actual disk won't be reflected until the cache is refreshed.

The issue here is that the `ready` event is fired **after** a generator is instantiated (the generator instance being passed as the first parameter to the event callback). As so, the file you create in the ready callback is already loaded in the memory file system and is set as non-existent.

Two possible fixes. To imitate a real environment, you can use `inTmpDir()` (or `inDir()`) callbacks to write the file:

```js
helpers.run(path.join(__dirname, '../subgenerator'))
  .inTmpDir(function (tmpDir) {
    fs.writeFileSync(
      path.join(tmpDir, 'package.json'),
      '{"name": "generator-foo", "files":[]}'
    );
  })
```

Or you can still use the `ready` event, but using the file system editor:

```js
helpers.run(path.join(__dirname, '../subgenerator'))
  .on('ready', function (generator) {
    generator.fs.write('package.json', '{"name": "generator-foo", "files":[]}');
  });
```
