### ISSUE TITLE
Add ability to add a humanized generator name

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#772]
Currently we just try to stylize the current slugified module name, but that is far from perfect.

Eg. with [`generator-gruntplugin`](https://github.com/yeoman/generator-gruntplugin) it would look better to have `Grunt Plugin` instead of the current `Gruntplugin`.

Eg. with [`generator-nm`](https://github.com/sindresorhus/generator-nm) I would like to use the name `Node Module` instead of `Nm`.

**Comment by SBoudrias** [comment]
Do you have a suggested way to achieve this goal?

**Comment by sindresorhus** [comment]
I think you're better suited to find a good way to achieve this, but I can suggest some ways:

- Add it as an export: `module.exports.generatorName = 'Node Module';`.
- Add it to `this` inside the generator. The problem is that everything is attached to `this`, which is so bad and will definitely lead to eventual conflict. So maybe `this.__generatorName__ = 'Node Module';`.

**Comment by SBoudrias** [comment]
Yeah, I was wondering because I don't really have a good idea.

The issue is that we cannot require/parse every generator on a user machine at runtime. This is to slow. That's why we're currently generating generators name out of folders name.

A solution might be to parse data out of a json file (either extra `package.json` keys or a new json config file). I'm not sure if the performance would be way better as we still need to require/parse all those json files...

As a side note, figuring this out with config could also help fixing: https://github.com/yeoman/environment/issues/12

**Comment by sindresorhus** [comment]
Ah, good point. Then I would go for a `generatorName` key in package.json. We already fetch the package.json.

Ideally required generator would be lazy until they were initiated, that way we could easily require them without too much overhead and have metadata on them.

**Comment by eddiemonge** [comment]
`yoGeneratorName`. Namespaced might be better, especially with generators in JS

**Comment by SBoudrias** [comment]
I've been thinking about this one and it doesn't make sense to load every `package.json` for the data. It'll be a huge performance hit.

A potential solution would be to return metadata wrapped in a special data type. This type of object would basically be a proxy allowing to lazy load only the data required by the caller.

Then we'd just need to make sure we are smart about accessing properties in `yo` to minimize the impact of name fetching.

**Comment by eddiemonge** [comment]
Should this be something that goes in the yo-rc file for each project?
