### ISSUE TITLE
Add bitbucket support

### ISSUE THREAD

**Issue by smesko85** [yeoman/generator#810]
Reading the API documentation, I found nice feature, but without bitbucket support.
http://yeoman.github.io/generator/fetch.html

**Comment by kevva** [comment]
Do you maybe mean http://yeoman.github.io/generator/remote.html?

**Comment by smesko85** [comment]
Yes. Sorry about that. It would be nice to have a way to interact with bitbucket repositories.

**Comment by rafaelgondim** [comment]
Or any git repository at anywhere

**Comment by SBoudrias** [comment]
We want to deprecate these features.

You can fetch from git directly using npm setting the dependencie version as a git url.

Is there any reason this is not working for you?

**Comment by rafaelgondim** [comment]
My template files are another project which the generator fetches every time he runs. So the templates are always update, because the "Template project" is under const development. Using as dependency I would have to run npm update likewise, and should be before the writing phase. But I've gone with the spawn method, you've got a point, it's so ease to do some workaround, we have so many options at the node environment , maybe it's better to have a smaller set of features well implemented and documented. Mark them as deprecated

**Comment by SBoudrias** [comment]
Yes, we will mark them in an upcoming release.

**Comment by smesko85** [comment]
@SBoudrias This is not working for me. I'm developing Yeoman generator at one repo, and other (i.e. frontend) dependencies on another, which are not npm packages. Please help.

**Comment by rafaelgondim** [comment]
To give you some ideias, this is how I'm doing:

```
var Q = require('q'),
    childProcess = require('child_process');

/**
 * @param Path, a directory that will hold de new repository, in the cache folder of Yeoman
 * @param repositoryUrl, The url, can be somithing like ssh://user@somwhere:/someFolder/repoName.git
 */
function gitClone(path, repositoryUrl) {

    return Q.Promise(function (resolve, reject) {

        var gitProcess = childProcess.spawn('git', ['clone', repositoryUrl, path]);

        gitProcess.on('error', function(err) {

            reject(err);

        });

        gitProcess.on('close', function (code) {

            if(!code)
                resolve();
            else
                reject();

        });

    });

};
```

**Comment by SBoudrias** [comment]
FWIW, you don't even need to launch a subprocess. npm can fetch git repo out of the box, it doesn't only fetch packages stored on npm.
