### ISSUE TITLE
Use `minimist` instead of `nopt`

### ISSUE THREAD

**Issue by kevva** [yeoman/generator#821]
To avoid conflicts with `yo` (which uses `minimist`) I think it would be best to use `minimist` here too. This doesn't come without some issues though. By default, `nopt` treats `--foo bar` as `foo: true` (which is really awkward) while `minimist` would parse it as `foo: bar`, if we haven't told it that `foo` is a boolean.

If we're ok with dropping the old behavior I think it would fix issues like https://github.com/yeoman/yo/issues/319 and potential future issues.

**Comment by arthurvr** [comment]
Sounds good :+1:

**Comment by SBoudrias** [comment]
Isn't yo using meow?

**Comment by arthurvr** [comment]
@SBoudrias Yes, and meow uses minimist.

**Comment by SBoudrias** [comment]
Ok duh.

Although, I'm not sure this is the right solution. We've been using nopt forever without any major issues. Issues started when yo switched to use meow instead of nopt.

Maybe the correct solution is to revert yo back to nopt and prevent the risk of very subtil backward incompatible changes.

-----------

FWIW the correct solution would be to redo this system to only parse on the yeoman-generator side. But it's too late to fix it.

**Comment by kevva** [comment]
I just think that having to write `--foo=bar` instead of `--foo bar` is weird. Someone would assume that the latter would *just work*.

**Comment by olsonpm** [comment]
Yeah the dependency between yo and generator is pretty strict.  Changing either would break a lot of existing code.  I'm not experienced enough to say whether a change would be worth it.

**Comment by SBoudrias** [comment]
Anyone wants to get their hands dirty working on this issue?
