### ISSUE TITLE
When composing generators, conflict ask multiple time to skip files

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#835]
Not sure what happened, but running generator-node, I've been asked multiple time to overwrite the same file. In all cases, I selected the "skip" option.

Every generators will run the write file phase, so my guess is skipping kept the file in mem-fs as modifief, so we asked multiple time (one per generator).

**Comment by kileniklawski** [comment]
I've been looking into this because it is an issue in JHipster. 

From what I can find, I think you're right that the file is being kept as modified, and not committed, leaving it in mem-fs.

I think it's actually the change event being invoked from the store.add call in the commitFilter that is causing the Base._writeFiles to be called again for “skipped” files. 

The first time the commit runs, the file state is deleted. The second time it runs, no files are added, so the commit filter never gets invoked, and it ends the cycle.

Let me know if this makes sense. If so, any ideas for the best approach to fix it?
