### ISSUE TITLE
`permission denied` while using `remote(url)`

### ISSUE THREAD

**Issue by csbun** [yeoman/generator#898]
I have generator code like this:

```javascript
        this.remote(
            'http://path/to/my.zip',
            function(err, remote) {
                console.log(err);
                console.log(remote);
            }
        );
```

Error output:

```
Error: EACCES: permission denied, scandir '/Users/hans/.cache/yeoman/http-path-to-my-zip/templates'
```

run `l -a /Users/hans/.cache/yeoman/http-path-to-my-zip` I get:

```
drwxr-xr-x  4 hans  staff   136B Feb  1 17:25 .
drwxr-xr-x  3 hans  staff   102B Feb  1 17:25 ..
----------  1 hans  staff   496B Feb  1 16:42 package.json
d---------  2 hans  staff    68B Feb  1 17:25 templates
```

p.s. I am using __node 4.2.4__ on __OS X 10.11.2__.

**Comment by SBoudrias** [comment]
This folder `/Users/hans/.cache` is not own by your current user. `chown` it to the correct user.

This probably happened because at some point you used `sudo` to do something. NEVER use sudo for anything. Fix your permissions instead.

**Comment by SBoudrias** [comment]
Actually, given the permissions are nothing. It's probably a chmod issue. So maybe your `umask` is broken.

Either way, that's a permission issue on your system. It has nothing to do with Yeoman.

**Comment by bowenliang123** [comment]
I am in the same situation with this ... Fairly enough if `chown` could help me out of it.
However, when we are developing a tool for someone else, this issue could be repeated on somewhere else which make it hard to balance. Quite hard to ask everyone chown the used `.cache` folder.
Is there any possible workaround like replacing the temporary folder path with current path in order to ensure we've got permission for it?

**Comment by SBoudrias** [comment]
@bowenliang123 most people don't break their cache folder. The thing about Unix permissions is that tools cannot control them - they are handled all the way by the user.
