### ISSUE TITLE
How to mock npmInstall() and spawnCommand()

### ISSUE THREAD

**Issue by hoisel** [yeoman/generator#918]
Hi,
How to mock this.npmInstall() and this.spawnCommand()? I'm using version 0.22.5.
I need to mock them in order to test code paths without actually installing dependencies.
Thanks

**Comment by dustinspecker** [comment]
Hey. I handled both of those cases with sinon over on [ng-poly](https://github.com/dustinspecker/generator-ng-poly/blob/4d810cbec1abc36d2cd7c77a085bac4fb675f7ad/test/test-app.js#L390).

**Comment by hoisel** [comment]
Thanks @dustinspecker ! That's worked for me!

**Comment by iamstarkov** [comment]
why do you need to mock `npmInstall`?

**Comment by dustinspecker** [comment]
It's just to be able to get code coverage on handling the if/else of `--skip-install`. We're installing other things (typings, etc.) besides npm and Bower.

**Comment by iamstarkov** [comment]
`istanbul disable` ?

**Comment by dustinspecker** [comment]
Yeah, you could do that, too.

**Comment by ErisDS** [comment]
I'm trying to stub the `yarnInstall` method. 

I used the approach in ng-poly, tried with promises, and without, and I couldn't get it to work.

```
.on('ready', (generator) => {
    gen = generator;

    generator.yarnInstall = sinon.spy()
})
```

Yarn install still gets called as though it hasn't been stubbed. Has anyone else got a better approach?

I notice in generator-node the problem is avoided by manually adding dependencies to package.json. However, that requires constant bumping of versions, whereas I want to use `this.yarnInstall` to install whatever the latest is.
