### ISSUE TITLE
Getting props from sub-generators

### ISSUE THREAD

**Issue by unional** [yeoman/generator#945]
Today we can pass arguments to sub-generators using `Options`. How to get props from the sub-generators?

One simple example:
I use `generator-license` to add LICENSE file to the project.
At the same time, I want to get the choice the user made so I can add it in `package.json`.

How to get access to the sub-generator instance (thus getting its `props`)?

**Comment by SBoudrias** [comment]
You cannot. Data only flows down in Yeoman composition.

So what are your option?

- generator-license can take care of everything, including adding the license to package.json
- Prompt for the license choice at the top level generator, then pass the value down to all the generator relying on that information.

**Comment by unional** [comment]
The first option is nice but not that feasible, because `package.json` is a template that require input from multiple sub-generator, e.g. `license`, `appname`, `testing`, etc.

The second option meaning the sub generators has to be breaking down by functions, i.e. one for prompt, one for writing, and may be one for installing. Also not optimal.

One way this can be solve is to have the `composeWith()` to return this object:
```js
{
  prompted: Promise,
  written: Promise,
  installed: Promise,
  ended: Promise
}
```
i.e. dictionary of promises that will resolve when each running context is completed.

**Comment by SBoudrias** [comment]
> The first option is nice but not that feasible

I don't see why. Just write to package.json multiple times.

**Comment by unional** [comment]
It does not work. `fs.copyTpl()` requires all fields to be specified. i.e.

```
// package.json
{
  <%- abc %>,
  <%- def %>
}
```

```js
fs.copyTpl(
  this.templatePath('package.json'),
  this.destinationPath('package.json'),
  {
    abc: '"a": "1"'
  });
```
will fail and the generator crash.
Also, even if that works, where to get the file? (i.e. `this.templatePath(...)`)
Say you have `sub-generator-a` and `sub-generator-b`, each touches `package.json`:
```js
// sub-generator-a
fs.copyTpl(???, ???, { fieldA: ... })
// sub-generator-b
fs.copyTpl(???, ???, { fieldB: ... })
```

**Comment by SBoudrias** [comment]
https://github.com/SBoudrias/mem-fs-editor#extendjsonfilepath-contents-replacer--space

**Comment by Sebastian-Fitzner** [comment]
Hi, 

first of all, great work with this eco system. What I do not understand is, why this issue is closed?
There are really some scenarios where it makes sense to access the props from sub generators. 

### The problem I face:  

I want to build mini generators which are responsible to display the prompts and save the answers in the store or in `.yo-rc.json`. After I have saved my answers the main generator - which composes the sub generators - scaffolds the project structure based on that config. 
That has an advantage, because I can share common generators which are not affecting the file system or are responsible for that. 

The problem is, that I have no access at all to these instances. Furthermore the save process of `yo-rc.json` is asynchronous, means I cannot use the context functions to save that file in `configuring()` and read that file in `writing()`. 

### Solutions?

I can think of multiple ways to handle that. 

1. Expose the props to the main generator
1. Extend the `Storage` class to give the possibility to write the config to the file system. 
    - For now it is saved in the internal store of the class and as I have seen so far `_persist()`, `save()` and `set()` are only working with that store property. 
    - A simple `saveToSystem()` method which accepts a callback function as parameter would be enough here ... (_BTW, I do not like that approach, but it would be a way to solve the issue_)

@SBoudrias What do you think? Is that something you would invest a bit time for? 

### Current workaround

**For anyone else or @Shpool**
Now I hacked it a bit. It is not nice but it is working. I just pass the `this.config` as `__store` option to the generator in `composeWith()`. It looks like that: 

**Main Generator**
``` js
module.exports = class extends Generator {
	prompting() {
	}

	initializing() {
		this.composeWith(require.resolve('../../../generator-generics/generators/app'), {
			__store: this.config
		});
	}

	writing() {
		console.log('config in spa: ', this.config.getAll());
	}
};
``` 

**Sub Generator**
``` js
module.exports = class extends Generator {
	prompting() {
		const prompts = [
			{
				type: 'input',
				name: 'projectName',
				message: 'Your project name',
				default: this.appname
			}
		];

		return this.prompt(prompts).then(props => {
			this.props = props;
		});
	}

	configuring() {
		this.options.__store.set('name', this.props.projectName);
		this.config.set('name', this.props.projectName);
	}

	writing() {
		this.fs.copyTpl(this.templatePath('gitignore'), '.gitignore');
		this.fs.copyTpl(this.templatePath('editorconfig'), '.editorconfig');
	}
};
```

I hope that helps others ...

**Comment by daKmoR** [comment]
@Sebastian-Fitzner thx for the workaround 👍 

tried to find an "official" way but it seems it's still not possible 😢

**Comment by cakriwut** [comment]
Hello all,

Recently I have same challenges, where I have:
1. sub-generator 1 prompt and do the work
2. sub-generator 2 will customize files/settings based on sub-generator 1 selections

Here is my approach:
1. I compose sub-generator 1, and then sub-generator 2
2. In the writing() of sub-generator 2, I read the content of in-memory files produced by sub-generator 1 so that I know what type if configuration used. For example I can readJson('package.json') produced by sub-generator 1.
3. I create in-memory configuration files for subsequence sub-generator.

Example: check generator-office-x in npm registry.

I hope it helps anyone who has same struggle.

Thanks
