### ISSUE TITLE
Ignore yo-rc for subgenerator

### ISSUE THREAD

**Issue by ingow** [yeoman/generator#947]
I can't ignore yo-rc root folder when I am running a subgenerator that should create files in the cwd.

I have a generator that uses a yo-rc file for a couple of subgenerators, but now I am trying to make a new subgenerator that must create the files in the CWD.

I tried to use process.cwd() but it's overwritten by yo-rc's path.

Is it possible to make a subgenerator blocks process.cwd from being overwritten?

**Comment by SBoudrias** [comment]
So this is currently not an option.

As a workaround, I'd suggest maybe taking the component you want to generate the files in as argument. e.g. `yo gen:sub route1`

**Comment by ingow** [comment]
Ok @SBoudrias, thanks for the reply!

I will pass it as an argument as you said.

**Comment by ericmorand** [comment]
So that's it? This is not an option?

What's the point of having the CWD changed by Yeoman? What are the benefits of this feature? What if we don't want to force our users to type long arguments when then just want to scaffold something in an already existing directory /a/very/long/path/with/a/lot/of/subdirectory?

This is a very annoying problem and it should be an option.

**Comment by ericmorand** [comment]
@SBoudrias I submitted a PR for this one. Would you mind looking at it? It's pretty small and safe and a test has been implemented.
