### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Bjr49000** [yeoman/generator#972]
I have this error when i install yeoman and i don't see help :
`npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!`
Thanks for you help.
(Win10, node 4)

**Comment by mischah** [comment]
It just is a warning. And that npm throws warnings during installation is pretty normal.
(And yeoman can’t get rid of that warning because it’s caused by a sub dependency)

So npm should have installed yeoman properly. 
Did you get yeoman running after that installation?
What happens after you type `yo` into your terminal after installation?
